### ISSUE TITLE
Error when  opening, creating, editing and saving graphql files

### ISSUE THREAD

**Issue by jarkin13** [prisma-labs/vscode-graphql#165]
I only using this for language syntax. 

## Actual Behavior
- Opening, creating, editing and saving `graphql` files results in an error

## Expected Behavior
- View `graphql` with language mode
- Being able to open, create, edit and save file without error

## Steps to Reproduce the Problem Or Description
- Create profile, specifically I have an `aws amplify` project
- `add api` to project
- Install GraphQL to vscode
- Open, create, edit and save `graphql` file without error

### GraphQL config file
```
// .graphqlconfig.yml
projects:
  xxx:
    schemaPath: amplify/backend/api/xxx/build/schema.graphql
    includes:
      - amplify/backend/api/xxx/schema.graphql
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/api.ts
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
```
## Specifications

  - GraphQL for VSCode Extension Version: 0.2.14
  - VSCode Version: 1.43.1
  - OS Name: Catalina
  - OS Version: 10.15.3

## Logs Of TS Server || GraphQL Language Service

Upon clicking within file
```
[Error - 7:00:37 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: No config found for uri: file:///Users/xxx/Workspace/xxx/amplify/backend/api/xxx/schema.graphql
  Code: -32603 
```

Upon editing file
```
(node:47615) UnhandledPromiseRejectionWarning: Error: No config found for uri: file:///Users/xxx/Workspace/xxx/amplify/backend/api/xxx/schema.graphql
    at GraphQLLanguageService.getConfigForURI (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-interface/dist/GraphQLLanguageService.js:20:15)
    at GraphQLLanguageService.getDiagnostics (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-interface/dist/GraphQLLanguageService.js:24:36)
    at /Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/dist/MessageProcessor.js:237:51
    at Array.map (<anonymous>)
    at MessageProcessor.handleDidChangeNotification (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/dist/MessageProcessor.js:233:32)
    at /Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/dist/startServer.js:103:48
    at handleNotification (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/node_modules/vscode-jsonrpc/lib/main.js:489:43)
    at processMessageQueue (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/node_modules/vscode-jsonrpc/lib/main.js:260:17)
    at Immediate.<anonymous> (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/node_modules/vscode-jsonrpc/lib/main.js:247:13)
    at processImmediate (internal/timers.js:439:21)
(node:47615) UnhandledPromiseRejectionWarning: Error: No config found for uri: file:///Users/xxx/Workspace/xxx/amplify/backend/api/xxx/schema.graphql
    at GraphQLLanguageService.getConfigForURI (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-interface/dist/GraphQLLanguageService.js:20:15)
    at GraphQLLanguageService.getDiagnostics (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-interface/dist/GraphQLLanguageService.js:24:36)
    at /Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/dist/MessageProcessor.js:237:51
    at Array.map (<anonymous>)
    at MessageProcessor.handleDidChangeNotification (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/dist/MessageProcessor.js:233:32)
    at /Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/dist/startServer.js:103:48
    at handleNotification (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/node_modules/vscode-jsonrpc/lib/main.js:489:43)
    at processMessageQueue (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/node_modules/vscode-jsonrpc/lib/main.js:260:17)
    at Immediate.<anonymous> (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/node_modules/vscode-jsonrpc/lib/main.js:247:13)
    at processImmediate (internal/timers.js:439:21)
(node:47615) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
(node:47615) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
(node:47615) UnhandledPromiseRejectionWarning: Error: No config found for uri: file:///Users/xxx/Workspace/xxx/amplify/backend/api/xxx/schema.graphql
    at GraphQLLanguageService.getConfigForURI (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-interface/dist/GraphQLLanguageService.js:20:15)
    at GraphQLLanguageService.getDiagnostics (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-interface/dist/GraphQLLanguageService.js:24:36)
    at /Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/dist/MessageProcessor.js:237:51
    at Array.map (<anonymous>)
    at MessageProcessor.handleDidChangeNotification (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/dist/MessageProcessor.js:233:32)
    at /Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/dist/startServer.js:103:48
    at handleNotification (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/node_modules/vscode-jsonrpc/lib/main.js:489:43)
    at processMessageQueue (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/node_modules/vscode-jsonrpc/lib/main.js:260:17)
    at Immediate.<anonymous> (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/node_modules/vscode-jsonrpc/lib/main.js:247:13)
    at processImmediate (internal/timers.js:439:21)
(node:47615) UnhandledPromiseRejectionWarning: Error: No config found for uri: file:///Users/xxx/Workspace/xxx/amplify/backend/api/xxx/schema.graphql
    at GraphQLLanguageService.getConfigForURI (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-interface/dist/GraphQLLanguageService.js:20:15)
    at GraphQLLanguageService.getDiagnostics (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-interface/dist/GraphQLLanguageService.js:24:36)
    at /Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/dist/MessageProcessor.js:237:51
    at Array.map (<anonymous>)
    at MessageProcessor.handleDidChangeNotification (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/dist/MessageProcessor.js:233:32)
    at /Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/dist/startServer.js:103:48
    at handleNotification (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/node_modules/vscode-jsonrpc/lib/main.js:489:43)
    at processMessageQueue (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/node_modules/vscode-jsonrpc/lib/main.js:260:17)
    at Immediate.<anonymous> (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/node_modules/vscode-jsonrpc/lib/main.js:247:13)
    at processImmediate (internal/timers.js:439:21)
(node:47615) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 17)
(node:47615) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 17)
```

Upon opening file
```
(node:47615) UnhandledPromiseRejectionWarning: Error: No config found for uri: file:///Users/xxx/Workspace/xxx/amplify/backend/api/xxx/schema.graphql
    at GraphQLLanguageService.getConfigForURI (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-interface/dist/GraphQLLanguageService.js:20:15)
    at GraphQLLanguageService.getDiagnostics (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-interface/dist/GraphQLLanguageService.js:24:36)
    at /Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/dist/MessageProcessor.js:176:51
    at Array.map (<anonymous>)
    at MessageProcessor.handleDidOpenOrSaveNotification (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/dist/MessageProcessor.js:172:32)
    at /Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/dist/startServer.js:89:48
    at handleNotification (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/node_modules/vscode-jsonrpc/lib/main.js:489:43)
    at processMessageQueue (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/node_modules/vscode-jsonrpc/lib/main.js:260:17)
    at Immediate.<anonymous> (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/node_modules/vscode-jsonrpc/lib/main.js:247:13)
    at processImmediate (internal/timers.js:439:21)
(node:47615) UnhandledPromiseRejectionWarning: Error: No config found for uri: file:///Users/xxx/Workspace/xxx/amplify/backend/api/xxx/schema.graphql
    at GraphQLLanguageService.getConfigForURI (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-interface/dist/GraphQLLanguageService.js:20:15)
    at GraphQLLanguageService.getDiagnostics (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-interface/dist/GraphQLLanguageService.js:24:36)
    at /Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/dist/MessageProcessor.js:176:51
    at Array.map (<anonymous>)
    at MessageProcessor.handleDidOpenOrSaveNotification (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/dist/MessageProcessor.js:172:32)
    at /Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/dist/startServer.js:89:48
    at handleNotification (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/node_modules/vscode-jsonrpc/lib/main.js:489:43)
    at processMessageQueue (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/node_modules/vscode-jsonrpc/lib/main.js:260:17)
    at Immediate.<anonymous> (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/node_modules/vscode-jsonrpc/lib/main.js:247:13)
    at processImmediate (internal/timers.js:439:21)
(node:47615) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:47615) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:47615) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:47615) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Error - 6:57:28 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: No config found for uri: file:///Users/xxx/Workspace/xxx/amplify/backend/api/xxx/schema.graphql
  Code: -32603 
```

Upon saving file
```
(node:47615) UnhandledPromiseRejectionWarning: Error: No config found for uri: file:///Users/xxx/Workspace/xxx/amplify/backend/api/xxx/schema.graphql
    at GraphQLLanguageService.getConfigForURI (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-interface/dist/GraphQLLanguageService.js:20:15)
    at GraphQLLanguageService.getDiagnostics (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-interface/dist/GraphQLLanguageService.js:24:36)
    at /Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/dist/MessageProcessor.js:176:51
    at Array.map (<anonymous>)
    at MessageProcessor.handleDidOpenOrSaveNotification (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/dist/MessageProcessor.js:172:32)
    at /Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/dist/startServer.js:96:48
    at handleNotification (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/node_modules/vscode-jsonrpc/lib/main.js:489:43)
    at processMessageQueue (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/node_modules/vscode-jsonrpc/lib/main.js:260:17)
    at Immediate.<anonymous> (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/node_modules/vscode-jsonrpc/lib/main.js:247:13)
    at processImmediate (internal/timers.js:439:21)
(node:47615) UnhandledPromiseRejectionWarning: Error: No config found for uri: file:///Users/xxx/Workspace/xxx/amplify/backend/api/xxx/schema.graphql
    at GraphQLLanguageService.getConfigForURI (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-interface/dist/GraphQLLanguageService.js:20:15)
    at GraphQLLanguageService.getDiagnostics (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-interface/dist/GraphQLLanguageService.js:24:36)
    at /Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/dist/MessageProcessor.js:176:51
    at Array.map (<anonymous>)
    at MessageProcessor.handleDidOpenOrSaveNotification (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/dist/MessageProcessor.js:172:32)
    at /Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/dist/startServer.js:96:48
    at handleNotification (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/node_modules/vscode-jsonrpc/lib/main.js:489:43)
    at processMessageQueue (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/node_modules/vscode-jsonrpc/lib/main.js:260:17)
    at Immediate.<anonymous> (/Users/xxx/.vscode/extensions/prisma.vscode-graphql-0.2.14/node_modules/graphql-language-service-server/node_modules/vscode-jsonrpc/lib/main.js:247:13)
    at processImmediate (internal/timers.js:439:21)
(node:47615) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 19)
(node:47615) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 19)
```

**Comment by cedricindra** [comment]
Same problem here. This post is the only reference I find to this issue so far.

**Comment by cedricindra** [comment]
Right, so. I figured out the source of the debugging messages (after having reinstalled and update watchmen to no avail [another story but I digress]).

If you have this graphql extension installed: https://github.com/prisma-labs/vscode-graphql, remove it and the outputs will stop. 

Let me know if this does the trick for you.

**Comment by mogarick** [comment]
@jarkin13 did you find a way to fix it? 
I have the plugin @cedricindra mentions because it is for a graphql lang server. It have its good benefits and that's why I want to keep using it. 
The thing is that it looks to be a problem in the way the `.graphqlconfig.yml` file created by amplify is set.

**Comment by Jupdi** [comment]
Same Problem here with Amplify. Any fixes?

**Comment by DeathsPirate** [comment]
I had this issue too, I've uninstalled and am now using the extension provided by Maxime Quandalle which doesn't have the issue and still provides nice highlighting.

**Comment by balmacefa** [comment]
Same Issue!

**Comment by balmacefa** [comment]
I add this line to the **.graphqlconfig.yml**:
```
projects:
  db:
      schemaPath: amplify/backend/api/**PROJECT_NAME**/build/schema.graphql
      includes: ["**/*.graphql"]
```
It solved the problem.

**Comment by acao** [comment]
huh! working on the `graphql-config@3.0.0` upgrade, I will see if i can re-create this. this may be a problem with [the LSP Server](https://github.com/graphql/graphiql/tree/main/packages/graphql-language-service-server)

**Comment by acao** [comment]
0.3.1 released! please open new tickets if you have any issues
